# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-11 21:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disenos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='disenador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100, unique=True, verbose_name='T\xedtulo')),
                ('descripcion', models.TextField()),
                ('presupuesto', models.IntegerField()),
                ('tiempo_registro', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='disenos',
            name='estado',
        ),
        migrations.AddField(
            model_name='comentario',
            name='estado',
            field=models.CharField(choices=[(0, 'En proceso'), (1, 'Disponible')], default='En proceso', max_length=100),
        ),
    ]
