# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('disenos', '0002_auto_20170311_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disenador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='comentario',
            name='Correo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Tu Correo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comentario',
            name='fecha_registro',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='Tu Nombre'),
            preserve_default=False,
        ),
    ]
