# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-13 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disenos', '0004_auto_20170313_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='imagen',
            field=models.ImageField(upload_to='images', verbose_name='Im\xe1gen'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.CharField(max_length=100, verbose_name='Comentario'),
        ),
    ]
